---
- hosts: all
  become: true
  tasks:
  - name: Install Apache2
    apt:
      name: apache2
  - name: Start apache on boot
    service:
      name: apache2
      state: started
      enabled: true
  - name: copy over SSH
    ansible.builtin.copy:
      src: index14.html
      dest: /var/www/html/index14.html
